fix: Adding overall format before appending ColumnFormatCodes
jackc/pgproto3 pull request #25
Opened 2022-03-29 21:10 UTC by masterkidan

Currently the encode method for copy_both_response is missing the OverallFormat as part of the 1st byte. This causes errors when using it. 

The issue is mainly seen while creating a 'mock' front-end for tests.

2022-03-30 20:17 UTC, gitstashpop requested changes
Hi, thanks for the patch!

I noticed that `copy_{in,out}_response` also have the same issue. Since these are all related, would you mind fixing that as well?

A unit test for at the least, encoding would also be awesome as well. Thanks!

2022-03-30 21:50 UTC, masterkidan commented
@gitstashpop I see that copy_{[in](https://github.com/jackc/pgproto3/blob/40ecac487c46292c2139a1fc7a7365be2a287ba6/copy_in_response.go#L52), [out](https://github.com/jackc/pgproto3/blob/40ecac487c46292c2139a1fc7a7365be2a287ba6/copy_out_response.go#L51)}_response do encode the OverallFormat ... Can you clarify the issue that you are referencing here?

2022-03-30 21:58 UTC, gitstashpop commented
> @gitstashpop I see that copy_{[in](https://github.com/jackc/pgproto3/blob/40ecac487c46292c2139a1fc7a7365be2a287ba6/copy_in_response.go#L52), [out](https://github.com/jackc/pgproto3/blob/40ecac487c46292c2139a1fc7a7365be2a287ba6/copy_out_response.go#L51)}_response do encode the OverallFormat ... Can you clarify the issue that you are referencing here?

Ah I missed that. Just the unit test then please.

2022-03-30 22:46 UTC, masterkidan commented
@gitstashpop added.

2022-03-30 23:04 UTC, gitstashpop requested changes

2022-03-30 23:04 UTC, gitstashpop commented on copy_both_response_test.go
> +	assert.DeepEqual(t, dst.ColumnFormatCodes, src.ColumnFormatCodes)
I think a meaningful test here would be to have a byte array with data you would expect on the wire, decode, encode, and then verify the encoded data equals what you initially saw.

2022-03-30 23:26 UTC, gitstashpop approved these changes

2022-03-30 23:26 UTC, gitstashpop commented on go.sum
> +gopkg.in/check.v1 v0.0.0-20161208181325-20d25e280405 h1:yhCVgyC4o1eVCa2tZl7eS0r+SDo693bJlVdllGtEeKM=
is this just leftover from the other iteration? probably can be dropped

2022-04-02 23:58 UTC, merged

2022-04-02 23:59 UTC, jackc commented
LGTM